PACKAGENAME=WireGuard_VPN
MENUNAME="WireGuard VPN"
VENDOR="Mo3he"
APPMAJORVERSION=1
APPMINORVERSION=2
APPMICROVERSION=15
APPTYPE=armv7hf
APPNAME=wireguardconfig
APPMAIN=wireguardconfig
APPOPTS=""
OTHERFILES="lib html index.html LICENSE"
SETTINGSPAGEFILE=index.html
LICENSE=
GRPNAME=
USERNAME=root
ARCHITECTURE=armv7hf
