PACKAGENAME=WireGuard_VPN
MENUNAME="WireGuard VPN"
VENDOR="Mo3he"
APPMAJORVERSION=VER_MAJOR
APPMINORVERSION=VER_MINOR
APPMICROVERSION=VER_MICRO
APPTYPE=armv7hf
APPNAME=wireguardconfig
APPMAIN=wireguardconfig
APPOPTS=""
OTHERFILES="lib html index.html LICENSE"
SETTINGSPAGEFILE=index.html
LICENSE=
GRPNAME=
USERNAME=root
ARCHITECTURE=armv7hf
